-- MySQL Script generated by MySQL Workbench
-- Mon Dec 10 19:56:14 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema prog4DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema prog4DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prog4DB` DEFAULT CHARACTER SET utf8 ;
USE `prog4DB` ;

-- -----------------------------------------------------
-- Table `prog4DB`.`appetizer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prog4DB`.`appetizers` (
  `FoodID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Price` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`FoodID`),
  UNIQUE INDEX `FoodID_UNIQUE` (`FoodID` ASC) )
ENGINE = InnoDB;

INSERT INTO appetizers VALUES
(0, 'Wings', 11.99),
(1, 'Nachos', 10.99),
(2, 'Cheese Sticks', 9.99);

-- -----------------------------------------------------
-- Table `prog4DB`.`salad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prog4DB`.`salads` (
  `FoodID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `saladcol` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`FoodID`),
  UNIQUE INDEX `FoodID_UNIQUE` (`FoodID` ASC) )
ENGINE = InnoDB;

INSERT INTO salads VALUES
(001, 'Caesar', 10.99),
(002, 'Taboulih', 11.99),
(003, 'Fattoush', 13.99);

-- -----------------------------------------------------
-- Table `prog4DB`.`cold_drink`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prog4DB`.`cold_drinks` (
  `DrinkID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Price` DECIMAL NOT NULL,
  PRIMARY KEY (`DrinkID`),
  UNIQUE INDEX `DrinkID_UNIQUE` (`DrinkID` ASC) )
ENGINE = InnoDB;

INSERT INTO cold_drinks  VALUES
(001, 'Bud Light', 8.99),
(002, 'Rolling Rock', 7.99),
(003, 'Miller Lite', 10.99);

-- -----------------------------------------------------
-- Table `prog4DB`.`hot_drinks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prog4DB`.`hot_drinks` (
  `DrinkID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Price` DECIMAL(5,2) NULL,
  PRIMARY KEY (`DrinkID`),
  UNIQUE INDEX `DrinkID_UNIQUE` (`DrinkID` ASC) )
ENGINE = InnoDB;

INSERT INTO hot_drinks VALUES
(001, 'Coffee', 6.99),
(002, 'Hot Chocolate',5.99),
(003, 'Tea', 6.99);

-- -----------------------------------------------------
-- Table `prog4DB`.`burgers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prog4DB`.`burgers` (
  `FoodID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Price` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`FoodID`),
  UNIQUE INDEX `FoodID_UNIQUE` (`FoodID` ASC) )
ENGINE = InnoDB;

INSERT INTO burgers VALUES
(001, 'Spicy Chicken', 13.99),
(002, 'Cheeseburger', 12.99),
(003, 'Sloppy', 14.99);


-- -----------------------------------------------------
-- Table `prog4DB`.`pancakes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prog4DB`.`pancakes` (
  `FoodID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Price` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`FoodID`),
  UNIQUE INDEX `FoodID_UNIQUE` (`FoodID` ASC) )
ENGINE = InnoDB;

INSERT INTO pancakes VALUES
(001, 'Chocolate Chip', 8.99),
(002, 'Strawberry', 9.99),
(003, 'Blueberry', 9.99);


-- -----------------------------------------------------
-- Table `prog4DB`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prog4DB`.`orders` (
  `OrderID` INT NOT NULL AUTO_INCREMENT,
  `Price` DECIMAL(5,2) NOT NULL,
  `Number_Of_Items` INT NOT NULL,
  `OrderName` VARCHAR(45) NOT NULL,
  `OrderItems` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`OrderID`),
  UNIQUE INDEX `OrderID_UNIQUE` (`OrderID` ASC) )
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


